version: "3.8"
services:
  server:
    build: .
    container_name: server
    ports:
      - "8000:8000"
    command: uvicorn Server.Server:app --host 0.0.0.0 --port 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  tests:
    build: .
    container_name: tests
    environment:
      - IS_DOCKERIZED=1
    depends_on:
      server:
        condition: service_healthy
    # Lance les tests unitaires/integration définis dans test/test_server.py
    command: pytest test/test_server.py --maxfail=1 --disable-warnings -q