name: Python Tests

on:
  push:
    branches:
      - clean
  pull_request:
    branches:
      - clean

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        run: docker compose build

      - name: Start server
        run: docker compose up -d server

      - name: Wait for server to be ready
        run: |
            echo "Waiting for server to be ready..."
            timeout=60
            elapsed=0
            url="http://localhost:8000/health"

            until curl --output /dev/null --silent --fail "$url"; do
                if [ $elapsed -ge $timeout ]; then
                    echo "Timeout waiting for server"
                    exit 1
                fi
                printf '.'
                sleep 2
                elapsed=$((elapsed+2))
            done

            echo "Server is up!"

      - name: Run tests
        run: docker compose up --exit-code-from test test
